name: Sync Upstream

on:
  schedule:
    - cron: '0 0 * * *' # 每天UTC时间0点执行
  workflow_dispatch: # 允许手动触发

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Add Upstream
        run: git remote add upstream https://github.com/celesWuff/waterctl.git

      - name: Fetch Upstream
        run: git fetch upstream

      - name: Merge Upstream
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git merge upstream/2.x --no-edit
          git push origin main –allow-unrelated-histories